<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-09-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_resolver', '0008_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
=======
# Generated by Django 3.0.5 on 2020-09-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_resolver', '0008_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
>>>>>>> edb34653d679429b0461f4c57d1574c628cb1793
